# Generated by Django 4.2.1 on 2023-06-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('cafe_name', models.CharField(max_length=255)),
                ('cafe_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('visitor_review_number', models.IntegerField()),
                ('blog_review_number', models.IntegerField()),
                ('cafe_phone_number', models.CharField(max_length=20)),
                ('cafe_info', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'db_table': 'Cafe',
            },
        ),
        migrations.CreateModel(
            name='CafeKeywords',
            fields=[
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.cafe')),
                ('dessert', models.DecimalField(decimal_places=10, max_digits=12)),
                ('well_being', models.DecimalField(decimal_places=10, max_digits=12)),
                ('various_menu', models.DecimalField(decimal_places=10, max_digits=12)),
                ('special_menu', models.DecimalField(decimal_places=10, max_digits=12)),
                ('pleasant_store', models.DecimalField(decimal_places=10, max_digits=12)),
                ('clean_store', models.DecimalField(decimal_places=10, max_digits=12)),
                ('background', models.DecimalField(decimal_places=10, max_digits=12)),
                ('parking', models.DecimalField(decimal_places=10, max_digits=12)),
                ('comfort', models.DecimalField(decimal_places=10, max_digits=12)),
                ('calm_down', models.DecimalField(decimal_places=10, max_digits=12)),
                ('trendy_store', models.DecimalField(decimal_places=10, max_digits=12)),
                ('unique_store', models.DecimalField(decimal_places=10, max_digits=12)),
                ('price', models.DecimalField(decimal_places=10, max_digits=12)),
                ('gift_packaging', models.DecimalField(decimal_places=10, max_digits=12)),
                ('alcohol', models.DecimalField(decimal_places=10, max_digits=12)),
                ('baby', models.DecimalField(decimal_places=10, max_digits=12)),
                ('service', models.DecimalField(decimal_places=10, max_digits=12)),
                ('activity', models.DecimalField(decimal_places=10, max_digits=12)),
                ('label', models.IntegerField()),
            ],
            options={
                'db_table': 'CafeKeywords',
            },
        ),
    ]
