# Generated by Django 4.2.1 on 2023-06-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafe_image',
            field=models.ImageField(blank=True, upload_to='cafes/images/'),
        ),
    ]
