# Generated by Django 4.2.1 on 2023-06-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='none', max_length=255)),
                ('user_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'EmailCode',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='none', max_length=255)),
                ('password', models.CharField(default='none', max_length=60)),
                ('name', models.CharField(default='none', max_length=255)),
                ('phone_no', models.CharField(default='none', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee')], max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('nickname', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('users.user',),
        ),
    ]
